# Generated by Django 5.1.6 on 2025-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
